kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "chatty.fullname" . }}-config
  labels: 
    {{-  include "chatty.labels" . | nindent 4 }}
data:
  REDIS_PORT: "{{ .Values.redis_port }}"
  REDIS_HOST: {{ .Values.redis_host }}